#===============
#     theme
#===============
import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]


#===============
# window config
#===============
[window]
# start mode
startup_mode = "Maximized"

# Padding
padding.x = 20
padding.y = 20

# noButton
decorations = "Buttonless"

# opacity
opacity = 0.6

# make Option key behave as Alt
option_as_alt = "Both"


#===============
#     Font
#===============
[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 16
