# theme
import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

#=====
# env
#=====
[env]
TERM = "xterm-256color"

#===============
# window config
#===============
[window]
# start mode
startup_mode = "Maximized"

# Padding
padding.x = 20
padding.y = 20

# noButton
decorations = "Buttonless"

# opacity
opacity = 0.8

# blur
blur = true

# make Option key behave as Alt
option_as_alt = "Both"


#======
# Font
#======
[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 24
